[package]
name = "cobalt_screenshot"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
bevy = { workspace = true }
cobalt_ron_assets = { path = "../cobalt_ron_assets" }
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
cobalt_test_utils = { path = "../cobalt_test_utils" }
tempfile = "3"

[features]
dynamic_linking = ["bevy/dynamic_linking"]

[lints]
workspace = true
