mod armor_form_ui;
mod attachment_form_ui;
mod autoload;
mod chrome;
mod damage_edit;
mod fire_mode_edit;
mod gang_form_ui;
mod injury_form_ui;
mod melee_weapon_form_ui;
mod mode_panels;
mod params;
pub(crate) mod prefab;
mod shell;
mod slots_edit;
mod sprite_form_ui;
mod sprite_thumb;
mod terrain_form_ui;
mod textures;
mod theme_combo;
mod theme_form_ui;
mod weapon_form_ui;

pub(crate) use prefab::nav::{level_nav_hotkeys, view_mode_hotkey};
pub(crate) use shell::editor_egui_ui;
