[package]
name = "gdtf_content_editor_bin"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gdtf_content_editor"
path = "src/main.rs"
doc = false

[dependencies]
gdtf_content_editor = { path = "../../crates/gdtf_content_editor" }

[features]
dynamic_linking = ["gdtf_content_editor/dynamic_linking"]
file_watcher = ["gdtf_content_editor/file_watcher"]

[lints]
workspace = true
