[package]
name = "gdtf_content_families"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
bevy = { workspace = true }
gdtf_assets = { path = "../gdtf_assets" }
cobalt_ron_assets = { path = "../../libs/cobalt_ron_assets" }
gdtf_battle_sim = { path = "../gdtf_battle_sim" }
serde = { workspace = true }

[dev-dependencies]
ron = { workspace = true }

[lints]
workspace = true
