[package]
name = "gdtf_screenshot"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
gdtf_test_utils = { path = "../gdtf_test_utils" }
tempfile = "3"

[features]
dynamic_linking = ["bevy/dynamic_linking"]

[lints]
workspace = true
