[package]
name = "gdtf_battle_input"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
gdtf_assets = { path = "../gdtf_assets" }
serde = { workspace = true }
gdtf_battle_presenter = { path = "../gdtf_battle_presenter" }
gdtf_battle_sim = { path = "../gdtf_battle_sim" }

[dev-dependencies]
bevy = { workspace = true }
gdtf_battle_sim = { path = "../gdtf_battle_sim", features = ["test-support"] }
ron = { workspace = true }
gdtf_test_utils = { path = "../gdtf_test_utils" }
gdtf_app = { path = "../gdtf_app", features = ["test-support"] }
gdtf_ui = { path = "../gdtf_ui" }

[lints]
workspace = true
