[package]
name = "gdtf_battle_input"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
bevy = { workspace = true }
cobalt_ron_assets = { path = "../../libs/cobalt_ron_assets" }
serde = { workspace = true }
gdtf_battle_presenter = { path = "../gdtf_battle_presenter" }
gdtf_battle_sim = { path = "../gdtf_battle_sim" }

[dev-dependencies]
bevy = { workspace = true }
gdtf_battle_sim = { path = "../gdtf_battle_sim" }
ron = { workspace = true }
cobalt_test_utils = { path = "../../libs/cobalt_test_utils" }
gdtf_game = { path = "../gdtf_game", features = ["headless_test"] }
gdtf_ui = { path = "../gdtf_ui" }

[lints]
workspace = true
